#省略数据源、数据分片、读写分离和数据脱敏配置

spring:
  shardingsphere:
    orchestration:
      name: zhili1 #治理实例名称
      overwrite: false #本地配置是否覆盖注册中心配置。如果可覆盖，每次启动都以本地配置为准
      registry:
        type: zookeeper #配置中心类型。如：zookeeper
        server-lists:  146.56.192.87:2181 #连接注册中心服务器的列表。包括IP地址和端口号。多个地址用逗号分隔。如: host1:2181,host2:2181
        namespace: test1 #注册中心的命名空间
        digest: 123456 #连接注册中心的权限令牌。缺省为不需要权限验证
        operation-timeout-milliseconds: zookeeper #操作超时的毫秒数，默认500毫秒
        max-retries: zookeeper #连接失败后的最大重试次数，默认3次
        retry-interval-milliseconds: zookeeper #重试间隔毫秒数，默认500毫秒
        time-to-live-seconds: zookeeper #临时节点存活秒数，默认60秒
        props: zookeeper #配置中心其它属性