server:
  servlet:
    context-path: /security
  port: 8888


#spring:
#  security:
#    user:
#      name: oyc
#      password: 123456
spring:
  datasource:
    url: jdbc:mysql://146.56.192.87:3306/oyc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: oyc
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
